name: Get circuitpython versions

on:
  workflow_dispatch:
  push:

jobs:

  cp_versions:
    name: Collect actual versions
    runs-on: ubuntu-latest
    outputs:
      all_versions: ${{ steps.get_cp_versions.outputs.all_versions }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (semver)
        run: |
          pip install semver

      - name: Determine mpy-cross versions
        id: get_cp_versions
        run: |
          # Call the function directly from a Python script.
          versions=$(python mpy_cross_circuit/versions.py)
          echo "MPY_VERSIONS=$versions" >> $GITHUB_ENV
          echo "::set-output name=all_versions::$versions" # Set output for other jobs