name: Get circuitpython versions

on:
  workflow_dispatch:
  push:

jobs:

  cp_versions:
    name: Collect actual versions
    runs-on: ubuntu-latest
    outputs:
      all_versions: ${{ steps.get_cp_versions.outputs.all_versions }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (semver)
        run: |
          pip install semver

      - name: Determine mpy-cross versions
        id: get_cp_versions
        run: |
          # Use the updated versions.py script
          versions=$(python mpy_cross_circuit/versions.py --json) # Get JSON output
          echo "Raw output: $versions"
          echo "::set-output name=all_versions::$versions" # Pass the raw JSON string
          echo "MPY_VERSIONS=$versions" >> $GITHUB_ENV # set the env

  check:
    name: Check versions format
    runs-on: ubuntu-latest
    needs: cp_versions
    strategy:
      matrix:
        cp_version: ${{ fromJson(needs.cp_versions.outputs.all_versions) }}

    steps:
      - name: Echo version
        run: |
          echo "Checking version: ${{ matrix.cp_version }}"
